/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.12
 * source: payload/v2/user/available_scopes.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class GetAvailableScopesResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        scopes?: string[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("scopes" in data && data.scopes != undefined) {
                this.scopes = data.scopes;
            }
        }
    }
    get scopes() {
        return pb_1.Message.getFieldWithDefault(this, 1, []) as string[];
    }
    set scopes(value: string[]) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        scopes?: string[];
    }): GetAvailableScopesResponse {
        const message = new GetAvailableScopesResponse({});
        if (data.scopes != null) {
            message.scopes = data.scopes;
        }
        return message;
    }
    toObject() {
        const data: {
            scopes?: string[];
        } = {};
        if (this.scopes != null) {
            data.scopes = this.scopes;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.scopes.length)
            writer.writeRepeatedString(1, this.scopes);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetAvailableScopesResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetAvailableScopesResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    pb_1.Message.addToRepeatedField(message, 1, reader.readString());
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetAvailableScopesResponse {
        return GetAvailableScopesResponse.deserialize(bytes);
    }
}
