/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.12
 * source: payload/v2/user/update.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../entity/user";
import * as pb_1 from "google-protobuf";
export class UpdateUserRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        userId?: number;
        newScopes?: string[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("userId" in data && data.userId != undefined) {
                this.userId = data.userId;
            }
            if ("newScopes" in data && data.newScopes != undefined) {
                this.newScopes = data.newScopes;
            }
        }
    }
    get userId() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set userId(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get newScopes() {
        return pb_1.Message.getFieldWithDefault(this, 2, []) as string[];
    }
    set newScopes(value: string[]) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        userId?: number;
        newScopes?: string[];
    }): UpdateUserRequest {
        const message = new UpdateUserRequest({});
        if (data.userId != null) {
            message.userId = data.userId;
        }
        if (data.newScopes != null) {
            message.newScopes = data.newScopes;
        }
        return message;
    }
    toObject() {
        const data: {
            userId?: number;
            newScopes?: string[];
        } = {};
        if (this.userId != null) {
            data.userId = this.userId;
        }
        if (this.newScopes != null) {
            data.newScopes = this.newScopes;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.userId != 0)
            writer.writeInt32(1, this.userId);
        if (this.newScopes.length)
            writer.writeRepeatedString(2, this.newScopes);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateUserRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateUserRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.userId = reader.readInt32();
                    break;
                case 2:
                    pb_1.Message.addToRepeatedField(message, 2, reader.readString());
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UpdateUserRequest {
        return UpdateUserRequest.deserialize(bytes);
    }
}
