/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.4
 * source: payload/v1/album/get.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../entity/photo";
import * as dependency_2 from "./../../../entity/album";
import * as pb_1 from "google-protobuf";
export class GetAlbumResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        album?: dependency_2.AlbumWithCoverPhoto;
        photos?: dependency_1.Photo[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("album" in data && data.album != undefined) {
                this.album = data.album;
            }
            if ("photos" in data && data.photos != undefined) {
                this.photos = data.photos;
            }
        }
    }
    get album() {
        return pb_1.Message.getWrapperField(this, dependency_2.AlbumWithCoverPhoto, 1) as dependency_2.AlbumWithCoverPhoto;
    }
    set album(value: dependency_2.AlbumWithCoverPhoto) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get hasAlbum() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get photos() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.Photo, 2) as dependency_1.Photo[];
    }
    set photos(value: dependency_1.Photo[]) {
        pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    static fromObject(data: {
        album?: ReturnType<typeof dependency_2.AlbumWithCoverPhoto.prototype.toObject>;
        photos?: ReturnType<typeof dependency_1.Photo.prototype.toObject>[];
    }): GetAlbumResponse {
        const message = new GetAlbumResponse({});
        if (data.album != null) {
            message.album = dependency_2.AlbumWithCoverPhoto.fromObject(data.album);
        }
        if (data.photos != null) {
            message.photos = data.photos.map(item => dependency_1.Photo.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            album?: ReturnType<typeof dependency_2.AlbumWithCoverPhoto.prototype.toObject>;
            photos?: ReturnType<typeof dependency_1.Photo.prototype.toObject>[];
        } = {};
        if (this.album != null) {
            data.album = this.album.toObject();
        }
        if (this.photos != null) {
            data.photos = this.photos.map((item: dependency_1.Photo) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.hasAlbum)
            writer.writeMessage(1, this.album, () => this.album.serialize(writer));
        if (this.photos.length)
            writer.writeRepeatedMessage(2, this.photos, (item: dependency_1.Photo) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetAlbumResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetAlbumResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.album, () => message.album = dependency_2.AlbumWithCoverPhoto.deserialize(reader));
                    break;
                case 2:
                    reader.readMessage(message.photos, () => pb_1.Message.addToRepeatedWrapperField(message, 2, dependency_1.Photo.deserialize(reader), dependency_1.Photo));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetAlbumResponse {
        return GetAlbumResponse.deserialize(bytes);
    }
}
