use crate::config::Config;
use crate::koala::{get_user_id_from_token, CredentialsType, UserIdFromTokenError};
use crate::routes::appdata::WebData;
use crate::routes::error::{Error, WebResult};
use crate::routes::redirect::Redirect;
use actix_web::http::StatusCode;
use actix_web::web;
use dal::database::{OAuthAccess, User};
use serde::Deserialize;
use tap::TapFallible;
use tracing::{trace, warn};

#[derive(Debug, Deserialize)]
pub struct Query {
    /// The OAuth code generated by Koala
    code: String,
}

/// Complete the Koala login flow.
/// The provided code must be generated by Koala.
///
/// Creates a session for the requesting user.
///
/// # Errors
///
/// - If the provided `code` isn't valid
/// - If something went wrong
pub async fn login(data: WebData, query: web::Query<Query>) -> WebResult<Redirect> {
    // Complete the OAuth2 flow by exchanging the code for a token pair
    trace!("Exchanging received code for Oauth2 tokens with Koala");
    let oauth_tokens = crate::koala::exchange_code(&data.config, &query.code)
        .await
        .map_err(Error::Koala)?;

    let is_admin = oauth_tokens.credentials_type == CredentialsType::Admin;
    trace!("Is signed-in user admin?: {is_admin}");

    let created_at_epoch =
        chrono::DateTime::parse_from_rfc3339(&oauth_tokens.created_at)?.timestamp();
    let expires_at = created_at_epoch - oauth_tokens.expires_in;
    let user = match User::get_by_id(&data.db, oauth_tokens.credentials_id).await? {
        Some(mut u) => {
            trace!("User already exists in database, setting new OAuth2 tokens");

            // Update the tokens for this user
            u.set_tokens(
                oauth_tokens.access_token,
                oauth_tokens.refresh_token,
                expires_at,
            )
            .await?;
            u
        }
        // No user exists yet, create one
        None => {
            trace!("User does not yet exist in database, creating new user.");

            let koala_id = get_user_id_from_token(&data.config, &oauth_tokens.access_token)
                .await
                .map_err(|e| match e {
                    UserIdFromTokenError::Reqwest(e) => Error::Koala(e),
                    UserIdFromTokenError::IntParse(e) => {
                        warn!("Failed to parse int: {e}");
                        Error::Other(StatusCode::INTERNAL_SERVER_ERROR)
                    }
                })?;

            let name = get_user_name(&data.config, koala_id, &oauth_tokens.access_token).await?;
            User::create(
                &data.db,
                koala_id,
                OAuthAccess {
                    access_token: oauth_tokens.access_token,
                    refresh_token: oauth_tokens.refresh_token,
                    expires_at,
                },
                is_admin,
                name,
            )
            .await?
        }
    };

    trace!("Creating new session for user.");
    let session_id = user.create_session().await?;
    let redirect_to = format!(
        "{}?session_id={}&is_admin={}",
        data.config.login_complete_redirect_uri, session_id, is_admin
    );
    Ok(Redirect::new(redirect_to))
}

async fn get_user_name(config: &Config, koala_id: i32, access_token: &str) -> WebResult<String> {
    // Retrieve the user's name
    let user_info = crate::koala::get_user_info(config, access_token, koala_id)
        .await
        .tap_err(|e| warn!("Failed to retrieve user info from Koala: {e}"))
        .map_err(Error::Koala)?;

    let user_name = if let Some(infix) = user_info.infix {
        format!("{} {} {}", user_info.first_name, infix, user_info.last_name)
    } else {
        format!("{} {}", user_info.first_name, user_info.last_name)
    };

    Ok(user_name)
}
